from enum import Enum

class Gender(Enum):
    MALE = "male"
    FEMALE = "female"

class Race(Enum):
    DWARF = "dwarf"
    WIZARD = "wizard"
    ELF = "elf"
    ORC = "orc"
    OGRE = "ogre"
    GOBLIN = "goblin"
    HUMAN = "human"
    TROLL = "troll"

class Occupation(Enum):
    LUMBERJACK = "lumberjack"
    FISHERMAN = "fisherman"
    HUNTER = "hunter"
    BUILDER = "builder"
    FARMER = "farmer"
    MEDIC = "medic"
    BREWER = "brewer"
    BLACKSMITH = "blacksmith"
    WARRIOR = "warrior"
    ARCHER = "archer"
    MERCHANT = "merchant"

class WeaponType(Enum):
    SWORD = "sword"
    GREAT_SWORD = "great_sword"
    AXE = "axe"
    GREAT_AXE = "great_axe"
    BOW = "bow"
    CROSSBOW = "crossbow"
    SPEAR = "spear"
    DAGGER = "dagger"
    STAFF = "staff"
    MACE = "mace"
    HAMMER = "hammer"
    WAR_HAMMER = "war_hammer"

class BodyPart(Enum):
    HEAD = "head"
    NECK = "neck"
    CHEST = "chest"
    BACK = "back"
    LEFT_ARM = "left_arm"
    RIGHT_ARM = "right_arm"
    LEFT_HAND = "left_hand"
    RIGHT_HAND = "right_hand"
    LEFT_LEG = "left_leg"
    RIGHT_LEG = "right_leg"
    LEFT_FOOT = "left_foot"
    RIGHT_FOOT = "right_foot"

class ArmorType(Enum):
    HELMET = "helmet"
    CHESTPLATE = "chestplate"
    GREAVES = "greaves"
    SABATON = "sabaton"
    GAUNTLETS = "gauntlets"
    ARMGUARD = "armguard"
    AMULET = "amulet"

class ArmorMaterial(Enum):
    LEATHER = "leather"
    IRON = "iron"
    STEEL = "steel"
    BRONZE = "bronze"
    GOLD = "gold"
    DIAMOND = "diamond"
    DRAGON_SCALE = "dragon_scale"
    MYTHRIL = "mythril"
    CLOTH = "cloth"
    WOOD = "wood"
    STONE = "stone"

class WeaponMaterial(Enum):
    WOOD = "wood"
    STONE = "stone"
    BRONZE = "bronze"
    IRON = "iron"
    STEEL = "steel"
    GOLD = "gold"
    DIAMOND = "diamond"
    MYTHRIL = "mythril"
    DRAGON_BONE = "dragon_bone"

class TreeType(Enum):
    OAK = "oak"
    WALNUT = "walnut"
    MAHOGANY = "mahogany"
    PINE = "pine"
    BAOBAB = "baobab"
    APPLE = "apple"
    OLIVE = "olive"
    ALMOND = "almond"

class PlantType(Enum):
    GRAPE = "grape"
    POTATO = "potato"
    CARROT = "carrot"
    COTTON = "cotton"
    BARLEY = "barley"
    WHEAT = "wheat"
    SUGARCANE = "sugarcane"
    CORN = "corn"

class AnimalType(Enum):
    SQUIRREL = "squirrel"
    SHEEP = "sheep"
    PIG = "pig"
    OX = "ox"
    BULL = "bull"
    CHICKEN = "chicken"
    HORSE = "horse"
    BOAR = "boar"
    RABBIT = "rabbit"
    BEAR = "bear"
    COW = "cow"
    PIRANHA = "piranha"
    SHARK = "shark"
    WHALE = "whale"
    GOAT = "goat"
    BEE = "bee"
    BIRD = "bird"
    DOG = "dog"
    CAT = "cat"
    FROG = "frog"
    LEECH = "leech"
    SNAKE = "snake"
    MINOTAUR = "minotaur"
    DRAGON = "dragon"
    CYCLOPS = "cyclops"
    SIREN = "siren"

class BossType(Enum):
    MINOTAUR = "minotaur"
    DRAGON = "dragon"
    CYCLOPS = "cyclops"

    SIREN = "siren"

class Biome(Enum):
    AQUATIC = "aquatic"
    FOREST = "forest"
    TUNDRA = "tundra"
    MOUNTAIN = "mountain"
    GRASSLAND = "grassland"
    DESERT = "desert"
    SWAMP = "swamp"
    UNDERGROUND = "underground"

class StructureType(Enum):
    STORAGE_CENTER = "storage_center"
    HOUSE = "house"
    WELL = "well"
    BARRACKS = "barracks"
    TRAINING_GROUND = "training_ground"
    FARM = "farm"
    MINE = "mine"
    FORGE = "forge"
    MARKET = "market"

class DisasterType(Enum):
    TORRENTIAL_RAIN = "torrential_rain"
    FIRE = "fire"
    AVALANCHE = "avalanche"
    EARTHQUAKE = "earthquake"
    FLOOD = "flood"
    BLIZZARD = "blizzard"
    VOLCANIC_ERUPTION = "volcanic_eruption"
    TORNADO = "tornado"
    DISEASE = "disease"

class RaceRelation(Enum):
    HOSTILE = "hostile"
    NEUTRAL = "neutral"
    FRIENDLY = "friendly"
    ALLIED = "allied"

class EventType(Enum):
    INVASION = "invasion"
    NATURAL_DISASTER = "natural_disaster"
    DISCOVERY = "discovery"
    DISEASE = "disease"
    RESOURCE_ABUNDANCE = "resource_abundance"
    CELEBRATION = "celebration"

